CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 6
PRINT_FREQ: 10

DATASET:
  DATASET: loveda
  ROOT: data/
  TEST_SET: 'list/loveda/val_rural.lst'
  TRAIN_SET: 'list/loveda/train_urban.lst'
  NUM_CLASSES: 7
MODEL:
  NAME: pidnet_small
  NUM_OUTPUTS: 2
  PRETRAINED: "./pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 1024
  - 1024
  BASE_SIZE: 1024
  BATCH_SIZE_PER_GPU: 6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.8
  NESTEROV: false
  FLIP: false
  MULTI_SCALE: false
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
  AUGMENTATION_TYPE: ['flip', 'color']
  AUG_PROB: 0.5
TEST:
  IMAGE_SIZE:
  - 1024
  - 1024
  BASE_SIZE: 1024
  BATCH_SIZE_PER_GPU: 6
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
