AUTO_RESUME: False

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASET:
  DATASET: loveda
  NUM_CLASSES: 7
  ROOT: /content/drive/MyDrive/AML_Segmentation_Project/data/LoveDA
  TRAIN_SET: /content/drive/MyDrive/AML_Segmentation_Project/PIDNet/data/list/loveda/Train/Rural/train.lst
  TEST_SET: /content/drive/MyDrive/AML_Segmentation_Project/PIDNet/data/list/loveda/Val/Rural/val.lst
  EXTRA_TRAIN_SET:

GPUS: (0,)

LOG_DIR: /content/drive/MyDrive/AML_Segmentation_Project/PIDNet/logs/pidnet_loveda_step_2b


LOSS:
  BALANCE_WEIGHTS: [0.4, 1.0]
  # CLASS_BALANCE: False
  OHEMKEEP: 100000
  OHEMTHRES: 0.9
  SB_WEIGHTS: 0.5
  USE_OHEM: True

MODEL:
  NAME: pidnet
  NUM_OUTPUTS: 2
  ALIGN_CORNERS: True
  PRETRAINED: /content/drive/MyDrive/AML_Segmentation_Project/PIDNet/pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar

OUTPUT_DIR: /content/drive/MyDrive/AML_Segmentation_Project/PIDNet/output/pidnet_loveda_step_2b


PIN_MEMORY: True

PRINT_FREQ: 20

TEST:
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 32
  FLIP_TEST: False
  IMAGE_SIZE: [1024, 1024]
  MODEL_FILE: 
  MULTI_SCALE: False
  OUTPUT_INDEX: -1

TRAIN:
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 4
  EXTRA_EPOCH: 0
  EXTRA_LR: 0.001
  FLIP: False
  IGNORE_LABEL: -1
  IMAGE_SIZE: [512, 512]
  LR: 0.01
  MOMENTUM: 0.9
  MULTI_SCALE: False
  NESTEROV: False
  OPTIMIZER: sgd
  RESUME: False
  SCALE_FACTOR:
  SHUFFLE: True
  WD: 0.0001

WORKERS: 4
